spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: mfirsov
    password: mfirsov
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false