spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false